# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "npm"
      - run: npm ci
      - run: npm run build

      - name: Set version
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "filename=$REPOSITORY-$VERSION" >> $GITHUB_OUTPUT

      - name: Create zip
        run: (cd dist && zip ${{ steps.version.outputs.filename }}.zip *.*)

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/${{ steps.version.outputs.filename }}.zip
